theme: jekyll-theme-minimal
encding: utf-8
title: 油層ノート
description:
url:
baseurl: "/notebook"
# logo: "assets/img/logo.png"
repository: https://github.com/mayuneko-re/notebook
plugins:
  - jekyll-sitemap
