theme: jekyll-theme-minimal
encding: utf-8
title: MAYUNEKO
description: 油層工学のノートブック
url:
baseurl: "/notebook"
logo: // "assets/img/logo.png"
repository: https://github.com/mayuneko-re/notebook
plugins:
  - jekyll-sitemap
